---
  #qa_url: https://workflow.dev.hautelook.net/login

  qa_url: https://qa-workflow1.dc1.lam.hautelook.net/login

  browserph: phantomjs
  browserff: firefox
  browserch: chrome
  username: pranay.dua@hautelook.com
  password: Welcome1!
